# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fuse-Simple
version:      1.00
version_from: lib/Fuse/Simple.pm
installdirs:  site
requires:
    Carp:                          0
    Errno:                         0
    Exporter:                      0
    Fcntl:                         0
    Fuse:                          0
    strict:                        0
    Switch:                        0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
